import type { NextPage } from 'next';
import Head from 'next/head';
import Banner from '../components/Banner';
import BlogTypes from '../components/BlogTypes';
import Footer from '../components/Footer';
import Nav from '../components/Nav';
import PubTypes from '../components/PubTypes';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Nav />
      </nav>
      <main>
        <Banner />
        <BlogTypes />
        <PubTypes />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
